### ISSUE TITLE
List of break exercises

### ISSUE THREAD

**Issue by magdalenakierat** [magdalenakierat/capstone-project#1]
## Value Proposition

**As a** user
**I need** a list of break exercises
**in order to** get inspiration for active breaks. 

## Description

<img width="200" alt="wireframe1" src="https://user-images.githubusercontent.com/106118696/179205455-90b77a7c-ca8b-4b4b-9259-663d042d43f8.png">

## Acceptance Criteria

- [x] Each break exercise is displayed in a different card.
- [x] Every card contains a category headline, a short exercise description, the repeat cycle in minutes and the duration in seconds or minutes. 
- [x] The list is scrollable.
- [x] The page title „Pausen“ is displayed. 

## Tasks

(for developers team)

- [x] Create global styles
- [x] Create component (card)
- [x] Add to Storybook
- [x] Write test
- [x] Create db.js with break exercises
- [x] Add to App
