### ISSUE TITLE
Create exercises

### ISSUE THREAD

**Issue by magdalenakierat** [magdalenakierat/capstone-project#10]
## Value proposition

**As a** user,
**I want to** create my own break exercises
**so that** I can save them in the app.

## Description

<img width="600" alt="wireframe 6" src="https://user-images.githubusercontent.com/106118696/182569683-c9e1b713-b0e0-4a2c-b145-b34cd77f771d.png"/>

## Acceptance criteria

- [ ] Screen 1: At the bottom of the page is a bar with a floating action button (FAB).
- [ ] FAB links to a form page (Screen 2).
- [ ] Form page has a title "Neue Pausenübung".
The form consists of 4 input sections, which are required:
- [ ] 1. a dropdown menu, which is used to select the category.
- [ ] 2. text input with the subheading "Beschreibung der Übung", where a free text is entered.
- [ ] 3. a dropdown menu with the subheading "Wiederholung", which is used to select the number of minutes.
- [ ] 4. two dropdown menus with the subheading "Dauer", the first dropdown is used to select the number of minutes and the second dropdown is used to select seconds or minutes.
- [ ] Button "Speichern" submits form.
- [ ] Button "Zurück" leads user back to Screen 1, without submitting the form. Inputs are reset. 
- [ ] If from is submitted, Screen 3 is shown with new exercise on top. 

## Tasks

- [ ] Create new feature branch "create"
- [ ] Create component BottomBar
- [ ] Create component CreateButton
- [ ] Create component Form
- [ ] Add React Router
- [ ] Write tests

**Comment by chris-yooo** [comment]
nice that you would the CRUD complete in your storys :)

1 nice improvement from me look at this site: https://material.io/components/buttons-floating-action-button#usage

they put the FAB in the right lower corner -> is this a nice improve for your app or you would fill the NAVbar on bottom with other buttons in future ?

chris
