### ISSUE TITLE
Delete exercises

### ISSUE THREAD

**Issue by magdalenakierat** [magdalenakierat/capstone-project#12]
## Value proposition

**As a** user,
**I want to** delete my own exercises
**so that** I have control over what I store in my app.

## Description
<img width="600" alt="wireframe 8" src="https://user-images.githubusercontent.com/106118696/182583790-6af48d98-6628-45c6-aaef-674199766010.png"/>

## Acceptance criteria

- [ ] Screen 1: All cards that were created by users include a "delete" action icon.
- [ ] The "delete" action icon deletes the card from the screen and the remaining cards take the free space.

## Tasks

- [ ] Create new feature branch "delete"
- [ ] Create component DeleteButton
- [ ] Update component Card
- [ ] Write tests

**Comment by magdalenakierat** [comment]
> Hey Magdalena,
> 
> Good job!
> 
> Only one suggestions: Maybe it would be nice to have a modal opening once the delete button is clicked, so that the user can confirm or abort the deletion of the exercise.

Thanks for the hint, dear Andrea 😊 I will definitely add this extra confirmation step to prevent the user from deleting something by mistake. I was planning to create a new issue for that. But maybe I will implement it already in this step.
