### ISSUE TITLE
Run breathing exercise

### ISSUE THREAD

**Issue by magdalenakierat** [magdalenakierat/capstone-project#13]
## Value proposition

**As a** user,
**I want to** run the existing breathing exercises
**so that** I get a visual support while following a certain breathing pattern.

## Description

<img width="600" alt="wireframe 9" src="https://user-images.githubusercontent.com/106118696/182616824-2c234b75-3151-40a9-a8ea-6992cdf6d4ce.png"/>

## Acceptance criteria

- [ ] Screen 1: All existing cards (not created by user) from the category "Atemübung" include a "play" action icon.
- [ ] "Play" action icon leads to animation page (Screen 2).
- [ ] Animation starts automatically.
- [ ] While showing the word "einatmen", the circle gets larger (Screen 2).
- [ ] After x seconds (depending on the breathing pattern in the description) the circle reaches it's largest state.
- [ ] While showing the word "ausatmen", the circle gets smaller (Screen 3).
- [ ] After x seconds (depending on the breathing pattern in the description) the circle reaches it's smallest state.
- [ ] There is a timer that starts at x minutes (depending on the duration set for the exercise) and counts down.
- [ ] When the timer reaches the 00:00 state, the exercise is canceled and Screen 1 is displayed again.
- [ ] By clicking on the screen, the exercise is canceled and screen 1 is displayed again.

## Tasks

- [ ] Create new feature branch "breathinganimation"
- [ ] Create component RunButton
- [ ] Update component Card
- [ ] Create component BreathingAnimation
- [ ] Write tests

**Comment by ahohnsen** [comment]
Hey Magdalena,

Nice job! Maybe it would be nice to have a cancel-button instead of canceling the exercise by clicking on the screen. 🤔 Or at least there should be an information displayed to the user that the exercise can be canceled by clicking on the screen. :)

**Comment by chris-yooo** [comment]
hey Magda i look at your second edit function US there is a edit Button at same position ? or you want to put the Buttons together or ?

**Comment by ahohnsen** [comment]
> hey Magda i look at your second edit function US there is a edit Button at same position ? or you want to put the Buttons together or ?
> 
> #11

As far as I understand, only the exercises in the category "breathing exercises" which are not created by the user will have a play-button. As well the user can only edit self-created exercises, therefore there should not be a button placement conflict. 🤔

**Comment by magdalenakierat** [comment]
> Hey Magdalena,
> 
> Nice job! Maybe it would be nice to have a cancel-button instead of canceling the exercise by clicking on the screen. 🤔 Or at least there should be an information displayed to the user that the exercise can be canceled by clicking on the screen. :)

Hey Andrea, thanks for your feedback! 🤗 For sure adding a cancel/return button would enhance the usability. I wanted to keep this issue small, that's why I haven't added this feature. But maybe I will do, since this should not be too time consuming.

**Comment by magdalenakierat** [comment]
> > hey Magda i look at your second edit function US there is a edit Button at same position ? or you want to put the Buttons together or ?
> > #11
> 
> As far as I understand, only the exercises in the category "breathing exercises" which are not created by the user will have a play-button. As well the user can only edit self-created exercises, therefore there should not be a button placement conflict. 🤔

Yes, that's right, this is only for exercises, which are not created by the user. So no button overload. 😉
