### ISSUE TITLE
Visual Design

### ISSUE THREAD

**Issue by magdalenakierat** [magdalenakierat/capstone-project#15]
## Value proposition

**As a** user,
**I want to** have a pleasant visual impression of my app
**so that** I can enjoy using it even more. 

## Description

<img width="800" alt="design" src="https://user-images.githubusercontent.com/106118696/183424532-9de66ad4-78f2-4701-94b5-f129b41f7ce1.png"/>

## Acceptance criteria

- [ ] The design template should be implemented in the code.
- [ ] Styling should be responsive (Screen "Desktop_Homepage)

## Tasks

- [ ] Create new feature branch "design"
- [ ] Update styled-components
- [ ] Update Storybook
