### ISSUE TITLE
Filter break exercises by category

### ISSUE THREAD

**Issue by magdalenakierat** [magdalenakierat/capstone-project#2]
## Value Proposition

**As a** user
**I need** to filter all break exercises by category
**in order to** have a better overview of the exercises that interest me at the moment.

## Description

<img width="400" alt="wireframe2" src="https://user-images.githubusercontent.com/106118696/179239093-f58a6afe-490d-441d-a686-a29b9ea7e1ff.png">

## Acceptance Criteria

- [x] A category section is displayed right above the list of cards.
- [x] The category section contains the headline „Kategorie“, one tag component per category and one tag representing all categories.
- [x] Screen 1: The „all“ tag is selected by default and all cards from all categories are displayed underneath.
- [x] The selected tag has a different styling than the not selected tags.
- [x] Screen 2: Only one tag can be selected at a time and only the cards corresponding to the selected category will be displayed.
- [x] The category section and the list is scrollable.

## Tasks

(for developers team)

- [x] Create feature branch
- [x] Create components (categories, tag)
- [x] Add styling
- [x] Add to Storybook
- [x] Write tests
- [x] Add to App
