### ISSUE TITLE
Filter bookmarks by category

### ISSUE THREAD

**Issue by magdalenakierat** [magdalenakierat/capstone-project#4]
## Value Proposition

**As a** user
**I need** to filter my bookmarks by category
**in order to** have a better overview of the bookmarks that interest me at the moment.

## Description

<img width="600" alt="wireframe 4" src="https://user-images.githubusercontent.com/106118696/179509475-653c7df0-a321-472b-939a-4f8bebec1ca7.png"/>

## Acceptance Criteria

- [ ] Screen 1: If „Favoriten“ and „Alle“ is selected, all bookmarked cards from all categories are displayed.
- [ ] Screen 2: If „Favoriten“ and e.g. „Augen“ is selected, all bookmarked cards from the „Augen“ category are displayed.
- [ ] Screen 3: If „Favoriten“ and a category is selected from which no favorite has been saved, a short paragraph is displayed, telling the user that there are no bookmarks in that specific category yet.
- [ ] Now two tags can be selected at a time, but only to combine a category with „Favoriten“. 
- [ ] It’s not possible to select two categories (e.g. „Augen“ and „Atem“) at once or to combine a category with „All“. 
- [ ] If „Favoriten“ is selected, „All“ is selected automatically, if no category was selected before.
- [ ] If „Favoriten“ is selected and the user clicks on the „Favoriten“ tag once again, it will be deselected and the selected category remains selected.
- [ ] It’s not possible to deselect a selected category tag by clicking on it. The user always needs to select a different category (or "Alle") to do so.

## Tasks

(for developers team)

- [ ] Create feature branch
- [ ] Add filter option (write logic & update component)
- [ ] Write tests
