### ISSUE TITLE
Local Storage

### ISSUE THREAD

**Issue by magdalenakierat** [magdalenakierat/capstone-project#8]
## Value proposition

**As a** user,
**I want to** to keep my bookmarks after a page refresh
**so that** I do not have to repeat my selection every time I use the app.

## Acceptance criteria

- [ ] If the user has set bookmarks, the corresponding cards are still marked after the page has been reloaded.

## Tasks

- [ ] Create new feature branch (localstorage)
- [ ] Add local storage
- [ ] Write test

**Comment by actyvystom** [comment]
Simply a nice one :slightly_smiling_face:!
